params:
  min_retweet_count: 10
  max_dairy_retweet: 400
  max_dairy_likes: 900
  min_followers_count: 20
  min_followers_extended: 500
  max_friends_count: 5000
  add_followers_count: 300
  mins_sleep: 15
  step_batch: 100
  max_batch: 300
  retweet_tracker: False
  follow_tracker: True
  retweet_watcher: False
  follow_watcher: False

languages:
  - es

words:
  block:
    - sex
    - sexo
    - tetas
    - polla
    - follar
    - verga
    - picha
    - co침o
    - mierdas

track:

  - EdpRNRMadrid
  - LondonMarathon
  - Maraton Madrid
  - maraton Madrid
  - marat칩n Madrid
  - Marat칩n Madrid
  - ExpoDepor
  - Marat칩nPopulardeMadrid
  - 42km

follow:
  - screen_name: SSVallecana
    user_id:     734711875938684929

   
