params:
  min_retweet_count: 10
  max_dairy_retweet: 400
  max_dairy_likes: 900
  min_followers_count: 70
  min_followers_extended: 500
  max_friends_count: 5000
  add_followers_count: 300
  mins_sleep: 15
  step_batch: 100
  max_batch: 300
  retweet_tracker: False
  follow_tracker: True
  retweet_watcher: False
  follow_watcher: False

languages:
  - es

words:
  block:
    - sex
    - sexo
    - tetas
    - polla
    - follar
    - verga
    - picha
    - co√±o
    - mierda

track:
  - EdpRNRMadrid
  - mi carrera en Strava
  - LondonMarathon

follow:
  - screen_name: SSVallecana
    user_id:     734711875938684929
  - screen_name: labicicletanet
    user_id:     437843937
  - screen_name: senderosalmeria
    user_id:     3872226215
  - screen_name: oscarregofpt
    user_id:     2902525197
  - screen_name: NandoPR70
    user_id:     841559698226712576
  - screen_name: JaviHds42k
    user_id:     378214401
  - screen_name: yolandahds
    user_id:     779882167
  - screen_name: jabatosrc
    user_id:     1969184156
  - screen_name: jjalesina
    user_id:     2911273129
  - screen_name: ConsuCM
    user_id:     418619624
  - screen_name: JuanFraHernande
    user_id:     426115682
  - screen_name: saezf_antonia
    user_id:     613522973
  - screen_name: alaureada
    user_id:    728215788734320640
