params:
  min_retweet_count: 10
  max_dairy_retweet: 400
  max_dairy_likes: 900
  min_followers_count: 70
  min_followers_extended: 500
  add_followers_count: 300
  mins_sleep: 15
  step_batch: 100
  max_batch: 300
  retweet_tracker: False
  follow_tracker: True
  retweet_watcher: False
  follow_watcher: False

words:
  block:
    - sex
    - sexo
    - tetas
    - polla
    - follar
    - verga
    - picha
    - co√±o
    - mierda

track:
  - SanSilvestreVallecana
  - san silvestre vallecana
  - VallecanaSoloHayUna
  - werunmad
  - SanSilvestreMini
  - madrid strava
  - strava resumen
  - strava carrera

follow:
  - screen_name: SSVallecana
    user_id:     734711875938684929
